[package]
name = "reposerve"
version = "0.1.0"
authors = ["Alexander von Gluck IV <kallisti5@unixzen.com>"]

[dependencies]
url = "*"
futures = "*"
hyper = "0.12"
regex = "*"
rust-s3 = "*"
toml = "0.4"
serde = "*"
serde_derive = "*"
