[package]
name = "hpkgbouncer"
version = "0.2.2"
authors = ["Alexander von Gluck IV <kallisti5@unixzen.com>"]

[dependencies]
natord = "1.0.9"
rocket = "0.4"
regex = "*"
rust-s3 = "0.26"
serde = "*"
toml = "0.4"
url = "*"
