[package]
name = "hpkgbouncer"
version = "0.5.0"
authors = ["Alexander von Gluck IV <alex@terarocket.io>"]
edition = "2024"

[dependencies]
natord = "1.0"
rocket = "0.5"
rocket_prometheus = "0.10"
regex = "*"
rust-s3 = { version = "0.35", features = ["default", "blocking"] }
serde = "*"
toml = "0.5"
url = "*"
