[countryA]
public_url = "https://cdn.haiku-os.org"
s3_endpoint = "https://cdn.haiku-os.org"
s3_bucket = "nightly"
s3_key = "A_KEY"
s3_secret = "A_SECRET"
# Optional
s3_region = ""
bucket_prefix = "/"

[countryB]
public_url = "https://cdn.haiku-os.org"
s3_endpoint = "https://cdn.haiku-os.org"
s3_bucket = "nightly"
s3_key = "A_KEY"
s3_secret = "A_SECRET"
# Optional
s3_region = ""
bucket_prefix = "/"
